import React from "react";
import Head from "next/head";
import { Navbar } from "../components";

export default function Layout(props) {
  return (
    <div>
      <Head>
        <title>{`${props?.title ?? ""} - Borneo Trans`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      {props.children}
    </div>
  );
}
